<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RecipeTagSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('recipe_tags')->insert([
            ['name' => 'Italian', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Pasta', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dinner', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Easy', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vegetarian', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gluten-Free', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Healthy', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quick', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Comfort Food', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Spicy', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vegan', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Low-Carb', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Family-Friendly', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'One-Pot', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Slow Cooker', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Grilling', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Baking', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dessert', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Breakfast', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Snack', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Holiday', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Seasonal', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Budget-Friendly', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kid-Friendly', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gourmet', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Fusion', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Classic', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Comforting', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Savory', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sweet', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nut-Free', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dairy-Free', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Low-Fat', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'High-Protein', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Low-Sugar', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Keto', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Paleo', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mediterranean', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Asian', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mexican', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Indian', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'French', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'American', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Middle Eastern', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Caribbean', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'African', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Latin American', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'European', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Asian Fusion', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Comfort Classics', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Holiday Favorites', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Seasonal Delights', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quick & Easy', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Meal Prep', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Leftover Makeovers', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Budget Meals', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Healthy Choices', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Family Favorites', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Crowd Pleasers', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gourmet at Home', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Comfort Food Classics', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Savory Delights', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sweet Treats', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nutritious & Delicious', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Flavorful & Fun', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Wholesome Meals', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Satisfying Snacks', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Decadent Desserts', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Refreshing Salads', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hearty Soups', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Flavorful Sauces', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Delicious Dips', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Perfect Pairings', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tasty Treats', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Satisfying Meals', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Flavorful Bites', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Comforting Classics', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Savory Snacks', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sweet & Savory', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Healthy & Hearty', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quick & Flavorful', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Easy & Delicious', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Flavorful & Filling', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Comforting & Cozy', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Satisfying & Scrumptious', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Wholesome & Warming', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Deliciously Different', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Flavorful Favorites', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tasty & Tempting', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Savory Sensations', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sweet Sensations', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Healthy & Happy', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Flavorful & Fun', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Comforting & Satisfying', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quick & Easy Meals', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Deliciously Simple', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Flavorful & Fresh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Satisfying & Savory', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Wholesome & Flavorful', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tasty & Nourishing', 'created_at' => now(), 'updated_at' => now()],
            // Add more tags as needed
        ]);
    }
}